Algoritmo "Combinacoes"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Rodrigo
// Data atual  : 29/07/2022
Var
// Seção de Declarações das variáveis 
   c1, c2: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Para c1 := 1 ate 3 faca
        Para c2 := 1 ate 3 faca
            EscrevaL (c1, c2)
        FimPara
   FimPara
Fimalgoritmo