Algoritmo "NumerosPares"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/07/2022
Var
// Seção de Declarações das variáveis 
   cont, V: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva ("Digite um valor: ")
   Leia (V)
   Se (V%2=1) entao
      V <- V - 1
   FimSe
   Para cont <- V ate 0 passo -2 faca
        EscrevaL (cont)
   FimPara
        

Fimalgoritmo
