Algoritmo "CalculoIdade"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Rodrigo
// Data atual  : 23/07/2022
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
         Escreva("Em que ano estamos? ")
         Leia (ano)
         Escreva("Em que ano você nasce? ")
         Leia (nasc)
         idade <- ano - nasc
         Escreva("Em ", ano, "você terá ", idade, " anos.")

Fimalgoritmo