Algoritmo "creuza_03"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Rodrigo
// Data atual  : 22/07/2022
Var
// Seção de Declarações das variáveis 
   F, C: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
         Escreva("Qual é a temperatura aqui? ")
         Leia(F)
         C <- (F - 32) / 1.8
         Escreva("No Brasil estaria: ", C:4:1)

Fimalgoritmo