Algoritmo "creuza_02"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Rodrigo
// Data atual  : 22/07/2022
Var
// Seção de Declarações das variáveis 
   reais, dolares: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
         Escreva("Quantos reais eu tenho? R$")
         Leia(reais)
         dolares <- reais/2.22
         Escreva("Posso ter US$", dolares)

Fimalgoritmo