Algoritmo "ParOuImpar"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Rodrigo
// Data atual  : 23/07/2022
Var
   // Seção de Declarações das variáveis
   n: Inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva("Escreva um número qualquer: ")
   Leia (n)
   Se (n % 2 = 0) entao
      Escreva ("O número ", n,  " é PAR")
   SeNao
      Escreva ("O número ", n,  " é IMPAR")
   FimSe
Fimalgoritmo