Algoritmo "MeuNome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Rodrigo
// Data atual  : 17/07/2022
Var
// Seção de Declarações das variáveis 
   Nome: Caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Nome <- "Gustavo"
   Escreva ("Digite seu nome: ")
   Leia (Nome)
   Escreva ("Muito Prazer ", Nome)

Fimalgoritmo